import type { IRoute, IUser } from '../models'

const LINKS = [
    { href: '/', text: 'О нас' },
    { href: '/', text: 'Как это работает' },
    { href: '/', text: 'Отзывы' },
    { href: '/', text: 'Контакты' },
]

const SOCIALS = [
    { icon: 'phone', value: '8 (800) 000 00 00', href: '#' },
    { icon: 'mail', value: 'inbox@mail.ru', href: '#' },
    { icon: 'skype', value: 'tu.train.tickets', href: '#' },
    {
        icon: 'geo',
        value: 'г. Москва \n ул. Московская 27-35\n 555 555',
        href: '#',
    },
]

const SUBSCRIPTIONS: string[] = [
    'youtube',
    'linkedin',
    'google',
    'facebook',
    'twitter',
]

const REVIEWS: IUser.Review[] = [
    {
        id: 1,
        img: '/avatars/avatar-1.png',
        name: 'Екатерина Вальнова',
        content: `Доброжелательные подсказки на всех этапах помогут правильно заполнить поля и без затруднений купить авиа или ж/д билет, даже если вы заказываете онлайн билет впервые.`,
    },
    {
        id: 2,
        img: '/avatars/avatar-1.png',
        name: 'Екатерина Вальнова',
        content: `Доброжелательные подсказки на всех этапах помогут правильно заполнить поля и без затруднений купить авиа или ж/д билет, даже если вы заказываете онлайн билет впервые.`,
    },
    {
        id: 3,
        img: '/avatars/avatar-1.png',
        name: 'Екатерина Вальнова',
        content: `Доброжелательные подсказки на всех этапах помогут правильно заполнить поля и без затруднений купить авиа или ж/д билет, даже если вы заказываете онлайн билет впервые.`,
    },
    {
        id: 4,
        img: '/avatars/avatar-1.png',
        name: 'Екатерина Вальнова',
        content: `Доброжелательные подсказки на всех этапах помогут правильно заполнить поля и без затруднений купить авиа или ж/д билет, даже если вы заказываете онлайн билет впервые.`,
    },
]

const SWITCHERS = [
    { id: 1, icon: 'coupe', name: 'Купе' },
    { id: 2, icon: 'plats', name: 'Платцкарт' },
    { id: 3, icon: 'seat', name: 'Сидячий' },
    { id: 4, icon: 'luxe', name: 'Люкс' },
    { id: 5, icon: 'wifi', name: 'Wi-Fi' },
    { id: 6, icon: 'express', name: 'Экспресс' },
]

const ROUTES: IRoute.Item[] = [
    {
        min_price: 123,
        have_air_conditioning: false,
        have_first_class: false,
        have_fourth_class: false,
        have_second_class: false,
        have_third_class: false,
        have_wifi: true,
        is_express: true,
        total_avaliable_seats: 123,
        arrival: {
            from: {
                city: 'Tumen',
                railway_station_name: 'asdasd',
                datetime: 123123123123123,
            },
            duration: 12123123123,
            train: '123123',
            to: {
                city: 'Moskva',
                railway_station_name: 'asdasd',
                datetime: 123123123123,
            },
            have_air_conditioning: false,
            have_first_class: false,
            have_fourth_class: false,
            have_second_class: false,
            have_third_class: false,
            have_wifi: false,
            is_express: false,
            min_price: 1000,
            price_info: '',
            seats_info: 'asd',
        },
        departure: {
            from: {
                city: 'Tumen',
                railway_station_name: 'asdasd',
                datetime: 123123123123123,
            },
            duration: 12123123123,
            train: '123123',
            to: {
                city: 'Moskva',
                railway_station_name: 'asdasd',
                datetime: 123123123123,
            },
            have_air_conditioning: false,
            have_first_class: false,
            have_fourth_class: false,
            have_second_class: false,
            have_third_class: false,
            have_wifi: false,
            is_express: false,
            min_price: 1000,
            price_info: '',
            seats_info: 'asd',
        },
    },
    {
        min_price: 123,
        have_air_conditioning: false,
        have_first_class: false,
        have_fourth_class: false,
        have_second_class: false,
        have_third_class: false,
        have_wifi: false,
        is_express: false,
        total_avaliable_seats: 123,
        arrival: {
            from: {
                city: 'Tumen',
                railway_station_name: 'asdasd',
                datetime: 123123123123123,
            },
            duration: 12123123123,
            train: '123123',
            to: {
                city: 'Moskva',
                railway_station_name: 'asdasd',
                datetime: 123123123123,
            },
            have_air_conditioning: false,
            have_first_class: false,
            have_fourth_class: false,
            have_second_class: false,
            have_third_class: false,
            have_wifi: false,
            is_express: false,
            min_price: 1000,
            price_info: '',
            seats_info: 'asd',
        },
        departure: {
            from: {
                city: 'Tumen',
                railway_station_name: 'asdasd',
                datetime: 123123123123123,
            },
            duration: 12123123123,
            train: '123123',
            to: {
                city: 'Moskva',
                railway_station_name: 'asdasd',
                datetime: 123123123123,
            },
            have_air_conditioning: false,
            have_first_class: false,
            have_fourth_class: false,
            have_second_class: false,
            have_third_class: false,
            have_wifi: false,
            is_express: false,
            min_price: 1000,
            price_info: '',
            seats_info: 'asd',
        },
    },
    {
        min_price: 123,
        have_air_conditioning: false,
        have_first_class: false,
        have_fourth_class: false,
        have_second_class: false,
        have_third_class: false,
        have_wifi: false,
        is_express: false,
        total_avaliable_seats: 123,
        arrival: {
            from: {
                city: 'Tumen',
                railway_station_name: 'asdasd',
                datetime: 123123123123123,
            },
            duration: 12123123123,
            train: '123123',
            to: {
                city: 'Moskva',
                railway_station_name: 'asdasd',
                datetime: 123123123123,
            },
            have_air_conditioning: false,
            have_first_class: false,
            have_fourth_class: false,
            have_second_class: false,
            have_third_class: false,
            have_wifi: false,
            is_express: false,
            min_price: 1000,
            price_info: '',
            seats_info: 'asd',
        },
        departure: {
            from: {
                city: 'Tumen',
                railway_station_name: 'asdasd',
                datetime: 123123123123123,
            },
            duration: 12123123123,
            train: '123123',
            to: {
                city: 'Moskva',
                railway_station_name: 'asdasd',
                datetime: 123123123123,
            },
            have_air_conditioning: false,
            have_first_class: false,
            have_fourth_class: false,
            have_second_class: false,
            have_third_class: false,
            have_wifi: false,
            is_express: false,
            min_price: 1000,
            price_info: '',
            seats_info: 'asd',
        },
    },
    {
        min_price: 123,
        have_air_conditioning: false,
        have_first_class: false,
        have_fourth_class: false,
        have_second_class: false,
        have_third_class: false,
        have_wifi: false,
        is_express: false,
        total_avaliable_seats: 123,
        arrival: {
            from: {
                city: 'Tumen',
                railway_station_name: 'asdasd',
                datetime: 123123123123123,
            },
            duration: 12123123123,
            train: '123123',
            to: {
                city: 'Moskva',
                railway_station_name: 'asdasd',
                datetime: 123123123123,
            },
            have_air_conditioning: false,
            have_first_class: false,
            have_fourth_class: false,
            have_second_class: false,
            have_third_class: false,
            have_wifi: false,
            is_express: false,
            min_price: 1000,
            price_info: '',
            seats_info: 'asd',
        },
        departure: {
            from: {
                city: 'Tumen',
                railway_station_name: 'asdasd',
                datetime: 123123123123123,
            },
            duration: 12123123123,
            train: '123123',
            to: {
                city: 'Moskva',
                railway_station_name: 'asdasd',
                datetime: 123123123123,
            },
            have_air_conditioning: false,
            have_first_class: false,
            have_fourth_class: false,
            have_second_class: false,
            have_third_class: false,
            have_wifi: false,
            is_express: false,
            min_price: 1000,
            price_info: '',
            seats_info: 'asd',
        },
    },
    {
        min_price: 123,
        have_air_conditioning: false,
        have_first_class: false,
        have_fourth_class: false,
        have_second_class: false,
        have_third_class: false,
        have_wifi: false,
        is_express: false,
        total_avaliable_seats: 123,
        arrival: {
            from: {
                city: 'Tumen',
                railway_station_name: 'asdasd',
                datetime: 123123123123123,
            },
            duration: 12123123123,
            train: '123123',
            to: {
                city: 'Moskva',
                railway_station_name: 'asdasd',
                datetime: 123123123123,
            },
            have_air_conditioning: false,
            have_first_class: false,
            have_fourth_class: false,
            have_second_class: false,
            have_third_class: false,
            have_wifi: false,
            is_express: false,
            min_price: 1000,
            price_info: '',
            seats_info: 'asd',
        },
        departure: {
            from: {
                city: 'Tumen',
                railway_station_name: 'asdasd',
                datetime: 123123123123123,
            },
            duration: 12123123123,
            train: '123123',
            to: {
                city: 'Moskva',
                railway_station_name: 'asdasd',
                datetime: 123123123123,
            },
            have_air_conditioning: false,
            have_first_class: false,
            have_fourth_class: false,
            have_second_class: false,
            have_third_class: false,
            have_wifi: false,
            is_express: false,
            min_price: 1000,
            price_info: '',
            seats_info: 'asd',
        },
    },
    {
        min_price: 123,
        have_air_conditioning: false,
        have_first_class: false,
        have_fourth_class: false,
        have_second_class: false,
        have_third_class: false,
        have_wifi: false,
        is_express: false,
        total_avaliable_seats: 123,
        arrival: {
            from: {
                city: 'Tumen',
                railway_station_name: 'asdasd',
                datetime: 123123123123123,
            },
            duration: 12123123123,
            train: '123123',
            to: {
                city: 'Moskva',
                railway_station_name: 'asdasd',
                datetime: 123123123123,
            },
            have_air_conditioning: false,
            have_first_class: false,
            have_fourth_class: false,
            have_second_class: false,
            have_third_class: false,
            have_wifi: false,
            is_express: false,
            min_price: 1000,
            price_info: '',
            seats_info: 'asd',
        },
        departure: {
            from: {
                city: 'Tumen',
                railway_station_name: 'asdasd',
                datetime: 123123123123123,
            },
            duration: 12123123123,
            train: '123123',
            to: {
                city: 'Moskva',
                railway_station_name: 'asdasd',
                datetime: 123123123123,
            },
            have_air_conditioning: false,
            have_first_class: false,
            have_fourth_class: false,
            have_second_class: false,
            have_third_class: false,
            have_wifi: false,
            is_express: false,
            min_price: 1000,
            price_info: '',
            seats_info: 'asd',
        },
    },
    {
        min_price: 123,
        have_air_conditioning: false,
        have_first_class: false,
        have_fourth_class: false,
        have_second_class: false,
        have_third_class: false,
        have_wifi: false,
        is_express: false,
        total_avaliable_seats: 123,
        arrival: {
            from: {
                city: 'Tumen',
                railway_station_name: 'asdasd',
                datetime: 123123123123123,
            },
            duration: 12123123123,
            train: '123123',
            to: {
                city: 'Moskva',
                railway_station_name: 'asdasd',
                datetime: 123123123123,
            },
            have_air_conditioning: false,
            have_first_class: false,
            have_fourth_class: false,
            have_second_class: false,
            have_third_class: false,
            have_wifi: false,
            is_express: false,
            min_price: 1000,
            price_info: '',
            seats_info: 'asd',
        },
        departure: {
            from: {
                city: 'Tumen',
                railway_station_name: 'asdasd',
                datetime: 123123123123123,
            },
            duration: 12123123123,
            train: '123123',
            to: {
                city: 'Moskva',
                railway_station_name: 'asdasd',
                datetime: 123123123123,
            },
            have_air_conditioning: false,
            have_first_class: false,
            have_fourth_class: false,
            have_second_class: false,
            have_third_class: false,
            have_wifi: false,
            is_express: false,
            min_price: 1000,
            price_info: '',
            seats_info: 'asd',
        },
    },
    {
        min_price: 123,
        have_air_conditioning: false,
        have_first_class: false,
        have_fourth_class: false,
        have_second_class: false,
        have_third_class: false,
        have_wifi: false,
        is_express: false,
        total_avaliable_seats: 123,
        arrival: {
            from: {
                city: 'Tumen',
                railway_station_name: 'asdasd',
                datetime: 123123123123123,
            },
            duration: 12123123123,
            train: '123123',
            to: {
                city: 'Moskva',
                railway_station_name: 'asdasd',
                datetime: 123123123123,
            },
            have_air_conditioning: false,
            have_first_class: false,
            have_fourth_class: false,
            have_second_class: false,
            have_third_class: false,
            have_wifi: false,
            is_express: false,
            min_price: 1000,
            price_info: '',
            seats_info: 'asd',
        },
        departure: {
            from: {
                city: 'Tumen',
                railway_station_name: 'asdasd',
                datetime: 123123123123123,
            },
            duration: 12123123123,
            train: '123123',
            to: {
                city: 'Moskva',
                railway_station_name: 'asdasd',
                datetime: 123123123123,
            },
            have_air_conditioning: false,
            have_first_class: false,
            have_fourth_class: false,
            have_second_class: false,
            have_third_class: false,
            have_wifi: false,
            is_express: false,
            min_price: 1000,
            price_info: '',
            seats_info: 'asd',
        },
    },
    {
        min_price: 123,
        have_air_conditioning: false,
        have_first_class: false,
        have_fourth_class: false,
        have_second_class: false,
        have_third_class: false,
        have_wifi: false,
        is_express: false,
        total_avaliable_seats: 123,
        arrival: {
            from: {
                city: 'Tumen',
                railway_station_name: 'asdasd',
                datetime: 123123123123123,
            },
            duration: 12123123123,
            train: '123123',
            to: {
                city: 'Moskva',
                railway_station_name: 'asdasd',
                datetime: 123123123123,
            },
            have_air_conditioning: false,
            have_first_class: false,
            have_fourth_class: false,
            have_second_class: false,
            have_third_class: false,
            have_wifi: false,
            is_express: false,
            min_price: 1000,
            price_info: '',
            seats_info: 'asd',
        },
        departure: {
            from: {
                city: 'Tumen',
                railway_station_name: 'asdasd',
                datetime: 123123123123123,
            },
            duration: 12123123123,
            train: '123123',
            to: {
                city: 'Moskva',
                railway_station_name: 'asdasd',
                datetime: 123123123123,
            },
            have_air_conditioning: false,
            have_first_class: false,
            have_fourth_class: false,
            have_second_class: false,
            have_third_class: false,
            have_wifi: false,
            is_express: false,
            min_price: 1000,
            price_info: '',
            seats_info: 'asd',
        },
    },
    {
        min_price: 123,
        have_air_conditioning: false,
        have_first_class: false,
        have_fourth_class: false,
        have_second_class: false,
        have_third_class: false,
        have_wifi: false,
        is_express: false,
        total_avaliable_seats: 123,
        arrival: {
            from: {
                city: 'Tumen',
                railway_station_name: 'asdasd',
                datetime: 123123123123123,
            },
            duration: 12123123123,
            train: '123123',
            to: {
                city: 'Moskva',
                railway_station_name: 'asdasd',
                datetime: 123123123123,
            },
            have_air_conditioning: false,
            have_first_class: false,
            have_fourth_class: false,
            have_second_class: false,
            have_third_class: false,
            have_wifi: false,
            is_express: false,
            min_price: 1000,
            price_info: '',
            seats_info: 'asd',
        },
        departure: {
            from: {
                city: 'Tumen',
                railway_station_name: 'asdasd',
                datetime: 123123123123123,
            },
            duration: 12123123123,
            train: '123123',
            to: {
                city: 'Moskva',
                railway_station_name: 'asdasd',
                datetime: 123123123123,
            },
            have_air_conditioning: false,
            have_first_class: false,
            have_fourth_class: false,
            have_second_class: false,
            have_third_class: false,
            have_wifi: false,
            is_express: false,
            min_price: 1000,
            price_info: '',
            seats_info: 'asd',
        },
    },
    {
        min_price: 123,
        have_air_conditioning: false,
        have_first_class: false,
        have_fourth_class: false,
        have_second_class: false,
        have_third_class: false,
        have_wifi: false,
        is_express: false,
        total_avaliable_seats: 123,
        arrival: {
            from: {
                city: 'Tumen',
                railway_station_name: 'asdasd',
                datetime: 123123123123123,
            },
            duration: 12123123123,
            train: '123123',
            to: {
                city: 'Moskva',
                railway_station_name: 'asdasd',
                datetime: 123123123123,
            },
            have_air_conditioning: false,
            have_first_class: false,
            have_fourth_class: false,
            have_second_class: false,
            have_third_class: false,
            have_wifi: false,
            is_express: false,
            min_price: 1000,
            price_info: '',
            seats_info: 'asd',
        },
        departure: {
            from: {
                city: 'Tumen',
                railway_station_name: 'asdasd',
                datetime: 123123123123123,
            },
            duration: 12123123123,
            train: '123123',
            to: {
                city: 'Moskva',
                railway_station_name: 'asdasd',
                datetime: 123123123123,
            },
            have_air_conditioning: false,
            have_first_class: false,
            have_fourth_class: false,
            have_second_class: false,
            have_third_class: false,
            have_wifi: false,
            is_express: false,
            min_price: 1000,
            price_info: '',
            seats_info: 'asd',
        },
    },
    {
        min_price: 123,
        have_air_conditioning: false,
        have_first_class: false,
        have_fourth_class: false,
        have_second_class: false,
        have_third_class: false,
        have_wifi: false,
        is_express: false,
        total_avaliable_seats: 123,
        arrival: {
            from: {
                city: 'Tumen',
                railway_station_name: 'asdasd',
                datetime: 123123123123123,
            },
            duration: 12123123123,
            train: '123123',
            to: {
                city: 'Moskva',
                railway_station_name: 'asdasd',
                datetime: 123123123123,
            },
            have_air_conditioning: false,
            have_first_class: false,
            have_fourth_class: false,
            have_second_class: false,
            have_third_class: false,
            have_wifi: false,
            is_express: false,
            min_price: 1000,
            price_info: '',
            seats_info: 'asd',
        },
        departure: {
            from: {
                city: 'Tumen',
                railway_station_name: 'asdasd',
                datetime: 123123123123123,
            },
            duration: 12123123123,
            train: '123123',
            to: {
                city: 'Moskva',
                railway_station_name: 'asdasd',
                datetime: 123123123123,
            },
            have_air_conditioning: false,
            have_first_class: false,
            have_fourth_class: false,
            have_second_class: false,
            have_third_class: false,
            have_wifi: false,
            is_express: false,
            min_price: 1000,
            price_info: '',
            seats_info: 'asd',
        },
    },
    {
        min_price: 123,
        have_air_conditioning: false,
        have_first_class: false,
        have_fourth_class: false,
        have_second_class: false,
        have_third_class: false,
        have_wifi: false,
        is_express: false,
        total_avaliable_seats: 123,
        arrival: {
            from: {
                city: 'Tumen',
                railway_station_name: 'asdasd',
                datetime: 123123123123123,
            },
            duration: 12123123123,
            train: '123123',
            to: {
                city: 'Moskva',
                railway_station_name: 'asdasd',
                datetime: 123123123123,
            },
            have_air_conditioning: false,
            have_first_class: false,
            have_fourth_class: false,
            have_second_class: false,
            have_third_class: false,
            have_wifi: false,
            is_express: false,
            min_price: 1000,
            price_info: '',
            seats_info: 'asd',
        },
        departure: {
            from: {
                city: 'Tumen',
                railway_station_name: 'asdasd',
                datetime: 123123123123123,
            },
            duration: 12123123123,
            train: '123123',
            to: {
                city: 'Moskva',
                railway_station_name: 'asdasd',
                datetime: 123123123123,
            },
            have_air_conditioning: false,
            have_first_class: false,
            have_fourth_class: false,
            have_second_class: false,
            have_third_class: false,
            have_wifi: false,
            is_express: false,
            min_price: 1000,
            price_info: '',
            seats_info: 'asd',
        },
    },
]

export const CONSTANTS = {
    LINKS,
    SOCIALS,
    SUBSCRIPTIONS,
    REVIEWS,
    SWITCHERS,
    ROUTES,
}
